autofetch_sources: True

networks:
  default: mainnet-fork

dotenv: .env

keys:
  ALCHEMYAPI_TOKEN: ${ALCHEMYAPI_TOKEN}
  ALCHEMYAPI_POLYGON_TOKEN: ${ALCHEMYAPI_POLYGON_TOKEN}
  WEB3_INFURA_PROJECT_ID: ${WEB3_INFURA_PROJECT_ID}
  ETHERSCAN_TOKEN: ${ETHERSCAN_TOKEN}
  BSCSCAN_TOKEN: ${BSCSCAN_TOKEN}
  ETHPLORER_API_KEY: ${ETHPLORER_API_KEY}
  POLYGONSCAN_TOKEN: ${POLYGONSCAN_TOKEN}
